  "skyline-residence": {
    title: "Skyline Residence",
    shortTitle: "Skyline Residence",
    location: "Dubai Marina, Dubai",
    locality: "Dubai Marina",
    city: "Dubai",
    country: "United Arab Emirates",
    propertyType: "Apartment",
    status: "Experience preview — not verified",
    price: "AED 3.25M",
    area: "1,985 sq.ft.",
    bedrooms: 3,
    bathrooms: 2,
  },
  "central-park-residence": {
    title: "Central Park Residence",
    shortTitle: "Central Park Residence",
    location: "Downtown Dubai",
    locality: "Downtown Dubai",
    city: "Dubai",
    country: "United Arab Emirates",
    propertyType: "Apartment",
    status: "Experience preview — not verified",
    price: "AED 2.10M",
    area: "1,240 sq.ft.",
    bedrooms: 2,
    bathrooms: 2,
  },
  "harbour-view-home": {
    title: "Harbour View Home",
    shortTitle: "Harbour View Home",
    location: "Singapore",
    locality: "Singapore",
    city: "Singapore",
    country: "Singapore",
    propertyType: "Residence",
    status: "Experience preview — not verified",
    price: "SGD 2.85M",
    area: "1,650 sq.ft.",
    bedrooms: 3,
    bathrooms: 2,
  },
  "modern-city-residence": {
    title: "Modern City Residence",
    shortTitle: "Modern City Residence",
    location: "Jumeirah Village Circle, Dubai",
    locality: "Jumeirah Village Circle",
    city: "Dubai",
    country: "United Arab Emirates",
    propertyType: "Apartment",
    status: "Owner-origin concept — not verified",
    price: "AED 1.35M",
    area: "1,180 sq.ft.",
    bedrooms: 2,
    bathrooms: 2,
  },
  "parkside-family-home": {
    title: "Parkside Family Home",
    shortTitle: "Parkside Family Home",
    location: "Singapore",
    locality: "Singapore",
    city: "Singapore",
    country: "Singapore",
    propertyType: "Residence",
    status: "Owner-origin concept — not verified",
    price: "SGD 2.20M",
    area: "1,540 sq.ft.",
    bedrooms: 3,
    bathrooms: 2,
  },
  "prime-urban-apartment": {
    title: "Prime Urban Apartment",
    shortTitle: "Prime Urban Apartment",
    location: "Minato, Tokyo",
    locality: "Minato",
    city: "Tokyo",
    country: "Japan",
    propertyType: "Apartment",
    status: "Owner-origin concept — not verified",
    price: "JPY 128M",
    area: "890 sq.ft.",
    bedrooms: 2,
    bathrooms: 1,
  },
  "palm-view-residence": {
    title: "Palm View Residence",
    shortTitle: "Palm View Residence",
    location: "Palm Jumeirah, Dubai",
    locality: "Palm Jumeirah",
    city: "Dubai",
    country: "United Arab Emirates",
    propertyType: "Villa",
    status: "Trust-signal concept — not verified",
    price: "AED 8.90M",
    area: "Preview information",
    bedrooms: 4,
    bathrooms: 4,
  },
  "central-garden-residence": {
    title: "Central Garden Residence",
    shortTitle: "Central Garden Residence",
    location: "Bukit Timah, Singapore",
    locality: "Bukit Timah",
    city: "Singapore",
    country: "Singapore",
    propertyType: "Residence",
    status: "Trust-signal concept — not verified",
    price: "SGD 3.40M",
    area: "Preview information",
    bedrooms: 3,
    bathrooms: 2,
  },
  "prime-metropolitan-home": {
    title: "Prime Metropolitan Home",
    shortTitle: "Prime Metropolitan Home",
    location: "Shibuya, Tokyo",
    locality: "Shibuya",
    city: "Tokyo",
    country: "Japan",
    propertyType: "Apartment",
    status: "Trust-signal concept — not verified",
    price: "JPY 145M",
    area: "Preview information",
    bedrooms: 2,
    bathrooms: 1,
  },
