import styles from "./PropertyDisclosure.module.css";

type PropertyDisclosureProps = Readonly<{
  verified: boolean;
  verificationLabel: string;
}>;

export default function PropertyDisclosure({
  verified,
  verificationLabel,
}: PropertyDisclosureProps) {
  return (
    <section className={styles.section}>
      <div className={styles.header}>
        <span className={styles.eyebrow}>IMPORTANT INFORMATION</span>
        <h2>Transparent property information.</h2>
      </div>

      <div className={styles.cards}>
        <article className={styles.card}>
          <span className={styles.icon}>✓</span>

          <div>
            <strong>
              {verified
                ? verificationLabel
                : "Verification information unavailable"}
            </strong>

            <p>
              Verification indicators shown by HOMIO must come from an
              authoritative capability and are not generated by the UI.
            </p>
          </div>
        </article>

        <article className={styles.card}>
          <span className={styles.icon}>i</span>

          <div>
            <strong>Indicative information</strong>

            <p>
              Price, availability, possession and other property details
              may change. Final information should be confirmed before
              commitment.
            </p>
          </div>
        </article>
      </div>
    </section>
  );
}
