
import type { PropertyRecord } from "./property.types";

/**
 * F04 experience preview only.
 * This is not authoritative REOS inventory.
 */
export const PROPERTY_PREVIEW: PropertyRecord = {
  id: "pune-kalyani-nagar-001",
  title: "Contemporary 3 BHK Residence",
  shortTitle: "Contemporary 3 BHK",
  location: "Kalyani Nagar, Pune",
  locality: "Kalyani Nagar",
  city: "Pune",
  country: "India",
  propertyType: "Apartment",
  status: "Ready to move — preview",
  price: "₹2.35 Cr",
  priceContext: "Experience preview value — not verified",
  area: "1,850 sq.ft.",
  bedrooms: 3,
  bathrooms: 3,
  parking: "2 covered",
  furnishing: "Semi-furnished",
  possession: "Preview information",
  projectId: "homio-kalyani-residences-001",
  projectName: "HOMIO Kalyani Residences",
  builderName: "Experience preview",
  description:
    "A HOMIO property-experience preview. Price, availability, ownership and property facts require authoritative verification.",
  verified: false,
  verificationLabel: "Verification pending",
  media: [
    { id: "media-01", label: "Living spaces", type: "image" },
    { id: "media-02", label: "Primary bedroom", type: "image" },
    { id: "media-03", label: "Floor plan", type: "floor-plan" },
    { id: "media-04", label: "Property walkthrough", type: "video" },
  ],
  amenities: [
    { label: "Parking", value: "Preview information" },
    { label: "Lift", value: "Preview information" },
    { label: "Security", value: "Preview information" },
    { label: "Gym", value: "Preview information" },
    { label: "Swimming Pool", value: "Preview information" },
    { label: "Power Backup", value: "Preview information" },
    { label: "Balcony", value: "Preview information" },
    { label: "Clubhouse", value: "Preview information" },
  ],
  highlights: [
    "Connected-location property discovery experience",
    "Structured property information",
    "Property decision-support layout",
    "Verification status displayed explicitly",
  ],
  nearby: [
    { label: "Airport", value: "Preview information" },
    { label: "Business district", value: "Preview information" },
    { label: "Schools", value: "Preview information" },
    { label: "Retail and dining", value: "Preview information" },
  ],
};

const PROPERTY_PREVIEW_VARIANTS: Record<
  string,
  Partial<PropertyRecord>
> = {
  "pune-koregaon-park-002": {
    title: "Refined 4 BHK Urban Villa",
    shortTitle: "Refined 4 BHK Villa",
    location: "Koregaon Park, Pune",
    locality: "Koregaon Park",
    propertyType: "Villa",
    status: "New launch — preview",
    price: "₹4.80 Cr",
    area: "3,200 sq.ft.",
    bedrooms: 4,
    bathrooms: 4,
  },
  "pune-baner-003": {
    title: "Modern 2 BHK City Home",
    shortTitle: "Modern 2 BHK Home",
    location: "Baner, Pune",
    locality: "Baner",
    propertyType: "Apartment",
    status: "Under construction — preview",
    price: "₹1.28 Cr",
    area: "1,220 sq.ft.",
    bedrooms: 2,
    bathrooms: 2,
  },
  "pune-viman-nagar-004": {
    title: "Premium 3 BHK Residence",
    shortTitle: "Premium 3 BHK",
    location: "Viman Nagar, Pune",
    locality: "Viman Nagar",
    propertyType: "Apartment",
    status: "Ready to move — preview",
    price: "₹1.95 Cr",
    area: "1,640 sq.ft.",
    bedrooms: 3,
    bathrooms: 3,
  },
  "pune-wakad-005": {
    title: "Family 3 BHK Smart Home",
    shortTitle: "Family 3 BHK Home",
    location: "Wakad, Pune",
    locality: "Wakad",
    propertyType: "Apartment",
    status: "New launch — preview",
    price: "₹1.12 Cr",
    area: "1,470 sq.ft.",
    bedrooms: 3,
    bathrooms: 2,
  },
  "pune-hinjewadi-006": {
    title: "Connected 2 BHK Investment Home",
    shortTitle: "Connected 2 BHK",
    location: "Hinjewadi, Pune",
    locality: "Hinjewadi",
    propertyType: "Apartment",
    status: "Under construction — preview",
    price: "₹89 Lakh",
    area: "1,060 sq.ft.",
    bedrooms: 2,
    bathrooms: 2,
  },
  "pune-magarpattacity-007": {
    title: "Executive 3 BHK Residence",
    shortTitle: "Executive 3 BHK",
    location: "Magarpatta City, Pune",
    locality: "Magarpatta City",
    propertyType: "Apartment",
    status: "Ready to move — preview",
    price: "₹1.72 Cr",
    area: "1,580 sq.ft.",
    bedrooms: 3,
    bathrooms: 3,
  },
  "pune-aundh-008": {
    title: "Elegant 4 BHK Residence",
    shortTitle: "Elegant 4 BHK",
    location: "Aundh, Pune",
    locality: "Aundh",
    propertyType: "Apartment",
    status: "Ready to move — preview",
    price: "₹2.85 Cr",
    area: "2,250 sq.ft.",
    bedrooms: 4,
    bathrooms: 4,
  },
  "skyline-residence": {
    title: "Skyline Residence",
    shortTitle: "Skyline Residence",
    location: "Dubai Marina, Dubai",
    locality: "Dubai Marina",
    city: "Dubai",
    country: "United Arab Emirates",
    propertyType: "Apartment",
    status: "Experience preview — not verified",
    price: "AED 3.25M",
    area: "1,985 sq.ft.",
    bedrooms: 3,
    bathrooms: 2,
  },
  "central-park-residence": {
    title: "Central Park Residence",
    shortTitle: "Central Park Residence",
    location: "Downtown Dubai",
    locality: "Downtown Dubai",
    city: "Dubai",
    country: "United Arab Emirates",
    propertyType: "Apartment",
    status: "Experience preview — not verified",
    price: "AED 2.10M",
    area: "1,240 sq.ft.",
    bedrooms: 2,
    bathrooms: 2,
  },
  "harbour-view-home": {
    title: "Harbour View Home",
    shortTitle: "Harbour View Home",
    location: "Singapore",
    locality: "Singapore",
    city: "Singapore",
    country: "Singapore",
    propertyType: "Residence",
    status: "Experience preview — not verified",
    price: "SGD 2.85M",
    area: "1,650 sq.ft.",
    bedrooms: 3,
    bathrooms: 2,
  },
  "modern-city-residence": {
    title: "Modern City Residence",
    shortTitle: "Modern City Residence",
    location: "Jumeirah Village Circle, Dubai",
    locality: "Jumeirah Village Circle",
    city: "Dubai",
    country: "United Arab Emirates",
    propertyType: "Apartment",
    status: "Owner-origin concept — not verified",
    price: "AED 1.35M",
    area: "1,180 sq.ft.",
    bedrooms: 2,
    bathrooms: 2,
  },
  "parkside-family-home": {
    title: "Parkside Family Home",
    shortTitle: "Parkside Family Home",
    location: "Singapore",
    locality: "Singapore",
    city: "Singapore",
    country: "Singapore",
    propertyType: "Residence",
    status: "Owner-origin concept — not verified",
    price: "SGD 2.20M",
    area: "1,540 sq.ft.",
    bedrooms: 3,
    bathrooms: 2,
  },
  "prime-urban-apartment": {
    title: "Prime Urban Apartment",
    shortTitle: "Prime Urban Apartment",
    location: "Minato, Tokyo",
    locality: "Minato",
    city: "Tokyo",
    country: "Japan",
    propertyType: "Apartment",
    status: "Owner-origin concept — not verified",
    price: "JPY 128M",
    area: "890 sq.ft.",
    bedrooms: 2,
    bathrooms: 1,
  },
  "palm-view-residence": {
    title: "Palm View Residence",
    shortTitle: "Palm View Residence",
    location: "Palm Jumeirah, Dubai",
    locality: "Palm Jumeirah",
    city: "Dubai",
    country: "United Arab Emirates",
    propertyType: "Villa",
    status: "Trust-signal concept — not verified",
    price: "AED 8.90M",
    area: "Preview information",
    bedrooms: 4,
    bathrooms: 4,
  },
  "central-garden-residence": {
    title: "Central Garden Residence",
    shortTitle: "Central Garden Residence",
    location: "Bukit Timah, Singapore",
    locality: "Bukit Timah",
    city: "Singapore",
    country: "Singapore",
    propertyType: "Residence",
    status: "Trust-signal concept — not verified",
    price: "SGD 3.40M",
    area: "Preview information",
    bedrooms: 3,
    bathrooms: 2,
  },
  "prime-metropolitan-home": {
    title: "Prime Metropolitan Home",
    shortTitle: "Prime Metropolitan Home",
    location: "Shibuya, Tokyo",
    locality: "Shibuya",
    city: "Tokyo",
    country: "Japan",
    propertyType: "Apartment",
    status: "Trust-signal concept — not verified",
    price: "JPY 145M",
    area: "Preview information",
    bedrooms: 2,
    bathrooms: 1,
  },
};

export function getPropertyPreview(
  propertyId: string,
): PropertyRecord | null {
  if (propertyId === PROPERTY_PREVIEW.id) {
    return { ...PROPERTY_PREVIEW };
  }

  const variant = PROPERTY_PREVIEW_VARIANTS[propertyId];

  if (!variant) {
    return null;
  }

  const record: PropertyRecord = {
    ...PROPERTY_PREVIEW,
    ...variant,
    id: propertyId,
    builderName: "Experience preview",
    description:
      "This is a property-experience preview for route and layout validation. Property facts, price and availability are not authoritatively verified.",
    priceContext: "Experience preview value — not verified",
    possession: "Preview information",
    verified: false,
    verificationLabel: "Verification pending",
  };

  delete record.projectId;
  delete record.projectName;

  return record;
}
